---
version: '3'
services:
  cloud9:
    build: .
    volumes:
      - workspace-data:/usr/src/app
    ports:
      - 8888:8888
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: Passw0rd
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd

volumes:
  mysql-data:
    driver: local
  workspace-data:
    driver: local
